// app/layout.tsx
import "./globals.css";
import type { Metadata } from "next";
import ClientLayout from "@/components/ClientLayout";
import { AuthProvider } from "@/contexts/auth/AuthProvider";

export const metadata: Metadata = {
    title: "My App",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="flex min-h-screen flex-col">
                <AuthProvider>
                    <ClientLayout>{children}</ClientLayout>
                </AuthProvider>
            </body>
        </html>
    );
}
